name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ${{ matrix.os }}
#     For running code on different os,versions of an apps or code libraries , matrix is used .
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macOS-latest]
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Thanks for making the pull request.'
